site_name: Pise1don's Homepage
theme:
  name: material
  language: zh
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.top
    - navigation.indexes
nav:
  - 高等数学助教专题:
    - 作业信息: 高等数学助教专题/作业信息.md
    - 作业反馈: 高等数学助教专题/作业反馈.md
    - 答疑精选: 高等数学助教专题/答疑精选.md
    # - 助教笔记: 高等数学助教专题/助教笔记.md

plugins:
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js